-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgjIB8Ja4KxmB5YfUw
xNWbITyycReFxhr3JaF6LThCqGGgCgYIKoZIzj0DAQehRANCAARliQZ+Vv8/Yk3B
lDWvS22rEwxIwUKk9jLIHzIZWujnncYRp3RwN/mxtp3aiHAi2gQ37e9d42KQJ7Jf
uXldyDnJ
-----END PRIVATE KEY-----